exports.readableperms = {
    CREATE_INSTANT_INVITE: "Create invite",
  KICK_MEMBERS: "Kick members",
  BAN_MEMBERS: "Ban members",
  ADMINISTRATOR: "Administrator",
  MANAGE_CHANNELS: "Manage channels",
  MANAGE_GUILD: "Manage server",
  ADD_REACTIONS: "Add reactions",
  VIEW_AUDIT_LOG: "View audit logs",
  PRIORITY_SPEAKER: "Priority speaker",
  STREAM: "Video",
  VIEW_CHANNEL: "View channel",
  SEND_MESSAGES: "Send messages",
  SEND_TTS_MESSAGES: "Send text-to-speech messages",
  MANAGE_MESSAGES: "Manage messages",
  EMBED_LINKS: "Embed links",
  ATTACH_FILES: "Attach files",
  READ_MESSAGE_HISTORY: "Read message history",
  MENTION_EVERYONE: "Mention @everyone, @here and all roles",
  USE_EXTERNAL_EMOJIS: "Use external emojis",
  VIEW_GUILD_INSIGHTS: "View server insights",
  CONNECT: "Connect",
  SPEAK: "Speak",
  MUTE_MEMBERS: "Mute members",
  DEAFEN_MEMBERS: "Deafen members",
  MOVE_MEMBERS: "Move members",
  USE_VAD: "Use voice activity detection",
  CHANGE_NICKNAME: "Change nickname",
  MANAGE_NICKNAMES: "Manage nicknames",
  MANAGE_ROLES: "Manage roles",
  MANAGE_WEBHOOKS: "Manage webhooks",
  MANAGE_EMOJIS_AND_STICKERS: "Manage emojis and stickers",
  USE_APPLICATION_COMMANDS: "Use application commands",
  REQUEST_TO_SPEAK: "Request to speak",
  MANAGE_THREADS: "Manage threads",
  USE_PUBLIC_THREADS: "Create public threads",
  USE_PRIVATE_THREADS: "Create private threads",
  USE_EXTERNAL_STICKERS: "Use external stickers",
  SEND_MESSAGES_IN_THREADS: "Send messages in threads",
  START_EMBEDDED_ACTIVITIES: "Use voice activity",
  MODERATE_MEMBERS: "timeout members",
} // permissions to readable permissions